services:
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
    exs_user.oauth_user_provider:
        class: EXS\GoogleOauthInviteBundle\Service\Auth\OAuthUserProvider
        arguments: [@doctrine.orm.entity_manager]