<?php

namespace EXS\GoogleOauthInviteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExsUserRepository extends EntityRepository {

    public function getUserByEmailQuery($email = '') {
        $query = $this->createQueryBuilder('u')
                ->where('u.email = :email')
                ->setParameter('email', $email)
                ->setMaxResults(1)
                ->getQuery();
        return $query;
    }

    public function getUserByEmail($email = '') {
        $query = $this->getUserByEmailQuery($email);
        $query->useResultCache(true, 600);
        $result = $query->getResult();

        if (count($result)) {
            return $result[0];
        }
        return $result;
    }

}
